import type { AppState } from './types'
import { DEFAULT_TAX_SETTINGS, DEFAULT_INTEGRATIONS, DEFAULT_EMAIL_TEMPLATES, DEFAULT_CLIENT_ROOM_CONFIG, DEFAULT_INTEGRATION_CREDENTIALS, DEFAULT_CALENDAR_SYNC_META, DEFAULT_TAX1099_SETTINGS, DEFAULT_BOOKKEEPING_SYNC_META, DEFAULT_SCHEDULING_META, DEFAULT_PLAID_SYNC_META, DEFAULT_CLOUD_STORAGE_META, DEFAULT_CLIENT_APP_LIFECYCLE } from './types'

export interface DemoSessionInfo {
  contractorName: string
  label: string
  mode: 'demo' | 'review'
}

const DEMO_CLIENT_IDS = {
  acme: 'demo-client-acme',
  bloom: 'demo-client-bloom',
  northstar: 'demo-client-northstar',
} as const

const DEMO_PROJECT_IDS = {
  rebrand: 'demo-project-rebrand',
  app: 'demo-project-app',
} as const

function daysAgo(n: number): string {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d.toISOString().split('T')[0]
}

function isoDaysAgo(n: number): string {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d.toISOString()
}

/** Synthetic sandbox data — never contains real user information. */
export function createDemoState(session?: DemoSessionInfo): AppState {
  const now = new Date().toISOString()
  const contractor = session?.contractorName || 'Demo Contractor Co.'
  const emailTemplates = DEFAULT_EMAIL_TEMPLATES.map((t) => ({
    ...t,
    id: crypto.randomUUID(),
    createdAt: now,
  }))

  return {
    profile: {
      name: contractor,
      email: 'demo@workvault-preview.example',
      phone: '(555) 010-0200',
      address: '100 Sandbox Lane',
      city: 'Demo City',
      state: 'CA',
      zip: '90210',
      taxId: 'XX-XXXXXXX',
      website: 'https://demo.workvault.example',
      logoUrl: '',
      defaultHourlyRate: 95,
      defaultCurrency: 'USD',
      invoicePrefix: 'DEMO-INV',
      contractPrefix: 'DEMO-CON',
      paymentMethods: [
        { id: 'demo-pm-1', type: 'bank_transfer', label: 'Demo Bank', details: 'Routing: XXXX · Account: XXXX (sample only)', enabled: true },
        { id: 'demo-pm-2', type: 'stripe', label: 'Stripe (Demo)', details: 'https://checkout.stripe.example/demo', enabled: true },
      ],
      defaultPaymentInstructions: 'This is a demo environment. No real payments will be processed.',
      industryId: 'software',
    },
    clients: [
      {
        id: DEMO_CLIENT_IDS.acme,
        name: 'Jordan Lee',
        email: 'jordan@acme-demo.example',
        phone: '(555) 111-2222',
        company: 'Acme Design Studio',
        address: '42 Sample Street, Demo City',
        notes: 'Sample client for preview purposes only.',
        portalToken: null,
        clientAppToken: null,
        appLifecycle: { ...DEFAULT_CLIENT_APP_LIFECYCLE },
        createdAt: isoDaysAgo(90),
      },
      {
        id: DEMO_CLIENT_IDS.bloom,
        name: 'Sam Rivera',
        email: 'sam@bloom-demo.example',
        phone: '(555) 333-4444',
        company: 'Bloom Marketing',
        address: '88 Preview Ave',
        notes: 'Demo account — not a real business.',
        portalToken: null,
        clientAppToken: null,
        appLifecycle: { ...DEFAULT_CLIENT_APP_LIFECYCLE },
        createdAt: isoDaysAgo(45),
      },
      {
        id: DEMO_CLIENT_IDS.northstar,
        name: 'Alex Chen',
        email: 'alex@northstar-demo.example',
        phone: '(555) 555-6666',
        company: 'Northstar Tech',
        address: '200 Sandbox Blvd',
        notes: '',
        portalToken: null,
        clientAppToken: null,
        appLifecycle: { ...DEFAULT_CLIENT_APP_LIFECYCLE },
        createdAt: isoDaysAgo(14),
      },
    ],
    timeEntries: [
      {
        id: 'demo-te-1',
        clientId: DEMO_CLIENT_IDS.acme,
        clientName: 'Acme Design Studio',
        projectId: DEMO_PROJECT_IDS.rebrand,
        projectName: 'Brand Refresh',
        description: 'Wireframes & mood boards',
        startTime: `${daysAgo(2)}T09:00:00`,
        endTime: `${daysAgo(2)}T12:30:00`,
        durationMinutes: 210,
        hourlyRate: 95,
        billable: true,
        invoiced: false,
        source: 'manual',
        externalId: null,
        createdAt: isoDaysAgo(2),
      },
      {
        id: 'demo-te-2',
        clientId: DEMO_CLIENT_IDS.bloom,
        clientName: 'Bloom Marketing',
        projectId: '',
        projectName: 'Q2 Campaign',
        description: 'Landing page build',
        startTime: `${daysAgo(1)}T14:00:00`,
        endTime: `${daysAgo(1)}T17:00:00`,
        durationMinutes: 180,
        hourlyRate: 95,
        billable: true,
        invoiced: false,
        source: 'manual',
        externalId: null,
        createdAt: isoDaysAgo(1),
      },
    ],
    contracts: [
      {
        id: 'demo-con-1',
        number: 'DEMO-CON-001',
        title: 'Website Redesign Agreement',
        clientId: DEMO_CLIENT_IDS.acme,
        clientName: 'Acme Design Studio',
        status: 'signed',
        template: 'standard',
        content: 'This is sample contract content for demonstration purposes only. No legal obligations apply in this preview environment.',
        startDate: daysAgo(60),
        endDate: daysAgo(-30),
        value: 12500,
        terms: '50% upfront, 50% on delivery. Sample terms only.',
        sentAt: isoDaysAgo(65),
        signedAt: isoDaysAgo(60),
        signatures: [],
        signingToken: null,
        docusignEnvelopeId: null,
        docusignSigningUrl: null,
        clientFileAccess: 'read',
        createdAt: isoDaysAgo(70),
        updatedAt: isoDaysAgo(60),
      },
    ],
    invoices: [
      {
        id: 'demo-inv-1',
        number: 'DEMO-INV-001',
        clientId: DEMO_CLIENT_IDS.acme,
        clientName: 'Acme Design Studio',
        status: 'sent',
        issueDate: daysAgo(10),
        dueDate: daysAgo(-5),
        lineItems: [
          { id: 'li-1', description: 'Brand strategy & discovery', quantity: 1, rate: 2500, amount: 2500 },
          { id: 'li-2', description: 'Visual identity design', quantity: 1, rate: 4500, amount: 4500 },
        ],
        subtotal: 7000,
        taxRate: 0,
        taxAmount: 0,
        total: 7000,
        notes: 'Demo invoice — not billable.',
        paymentMethodIds: ['demo-pm-1', 'demo-pm-2'],
        paymentInstructions: 'Sample payment instructions only.',
        sentAt: isoDaysAgo(10),
        paidAt: null,
        stripeCheckoutUrl: null,
        stripeSessionId: null,
        paymentLinks: [],
        createdAt: isoDaysAgo(10),
      },
      {
        id: 'demo-inv-2',
        number: 'DEMO-INV-002',
        clientId: DEMO_CLIENT_IDS.bloom,
        clientName: 'Bloom Marketing',
        status: 'paid',
        issueDate: daysAgo(30),
        dueDate: daysAgo(15),
        lineItems: [
          { id: 'li-3', description: 'Campaign landing page', quantity: 1, rate: 3200, amount: 3200 },
        ],
        subtotal: 3200,
        taxRate: 0,
        taxAmount: 0,
        total: 3200,
        notes: '',
        paymentMethodIds: ['demo-pm-1'],
        paymentInstructions: '',
        sentAt: isoDaysAgo(30),
        paidAt: isoDaysAgo(18),
        stripeCheckoutUrl: null,
        stripeSessionId: null,
        paymentLinks: [],
        createdAt: isoDaysAgo(30),
      },
    ],
    licenses: [
      {
        id: 'demo-lic-1',
        name: 'Adobe Creative Cloud',
        number: 'DEMO-LIC-001',
        issuingBody: 'Adobe',
        type: 'Software',
        status: 'active',
        issueDate: daysAgo(365),
        expiryDate: daysAgo(-180),
        verificationUrl: '',
        documentUrl: '',
        notes: 'Sample license entry',
        createdAt: isoDaysAgo(365),
      },
    ],
    workProtections: [
      {
        id: 'demo-wp-1',
        title: 'Logo Concepts v2',
        type: 'copyright',
        projectId: DEMO_PROJECT_IDS.rebrand,
        projectName: 'Brand Refresh',
        description: 'Copyright registration for logo concepts',
        hash: 'demo-hash-abc123',
        timestamp: isoDaysAgo(5),
        evidence: 'demo-evidence-hash',
        clientId: DEMO_CLIENT_IDS.acme,
        clientName: 'Acme Design Studio',
        createdAt: isoDaysAgo(5),
      },
    ],
    hostedProjects: [
      {
        id: 'demo-host-1',
        title: 'Acme Staging Site',
        description: 'Client staging environment',
        url: 'https://staging.demo.example',
        clientId: DEMO_CLIENT_IDS.acme,
        clientName: 'Acme Design Studio',
        status: 'live',
        deliverables: ['Homepage', 'About'],
        deployedAt: isoDaysAgo(30),
        createdAt: isoDaysAgo(120),
      },
    ],
    workRecords: [
      {
        id: 'demo-wr-1',
        title: 'Delivered brand guidelines PDF',
        type: 'deliverable',
        clientId: DEMO_CLIENT_IDS.acme,
        clientName: 'Acme Design Studio',
        projectId: DEMO_PROJECT_IDS.rebrand,
        projectName: 'Brand Refresh',
        description: 'Sample deliverable log',
        hoursSpent: 4,
        attachments: [],
        tags: ['branding'],
        createdAt: isoDaysAgo(7),
      },
    ],
    projects: [
      {
        id: DEMO_PROJECT_IDS.rebrand,
        title: 'Brand Refresh',
        clientId: DEMO_CLIENT_IDS.acme,
        clientName: 'Acme Design Studio',
        stage: 'active',
        value: 12500,
        description: 'Full brand identity overhaul',
        startDate: daysAgo(45),
        dueDate: daysAgo(-14),
        createdAt: isoDaysAgo(50),
        updatedAt: isoDaysAgo(2),
      },
      {
        id: DEMO_PROJECT_IDS.app,
        title: 'Mobile App MVP',
        clientId: DEMO_CLIENT_IDS.northstar,
        clientName: 'Northstar Tech',
        stage: 'proposal',
        value: 28000,
        description: 'iOS/Android MVP build',
        startDate: daysAgo(7),
        dueDate: daysAgo(-60),
        createdAt: isoDaysAgo(14),
        updatedAt: isoDaysAgo(7),
      },
    ],
    proposals: [
      {
        id: 'demo-prop-1',
        number: 'DEMO-PRO-001',
        title: 'Mobile App MVP Proposal',
        clientId: DEMO_CLIENT_IDS.northstar,
        clientName: 'Northstar Tech',
        status: 'sent',
        lineItems: [
          { id: 'pli-1', description: 'Discovery & UX', quantity: 1, rate: 5000, amount: 5000 },
          { id: 'pli-2', description: 'Development sprint 1', quantity: 1, rate: 12000, amount: 12000 },
        ],
        subtotal: 17000,
        total: 17000,
        validUntil: daysAgo(-21),
        notes: 'Sample proposal for preview',
        createdAt: isoDaysAgo(10),
        updatedAt: isoDaysAgo(8),
      },
    ],
    expenses: [
      {
        id: 'demo-exp-1',
        description: 'Stock photography',
        amount: 89,
        category: 'materials',
        date: daysAgo(12),
        clientId: DEMO_CLIENT_IDS.acme,
        clientName: 'Acme Design Studio',
        projectId: DEMO_PROJECT_IDS.rebrand,
        projectName: 'Brand Refresh',
        billable: true,
        invoiced: false,
        mileage: 0,
        notes: '',
        createdAt: isoDaysAgo(12),
      },
    ],
    recurringInvoices: [],
    scopeEntries: [
      {
        id: 'demo-scope-1',
        title: 'Additional icon set',
        description: 'Client requested 12 extra icons outside original scope',
        clientId: DEMO_CLIENT_IDS.acme,
        clientName: 'Acme Design Studio',
        projectId: DEMO_PROJECT_IDS.rebrand,
        projectName: 'Brand Refresh',
        requestedBy: 'Jordan Lee',
        estimatedHours: 6,
        billable: true,
        invoiced: false,
        createdAt: isoDaysAgo(3),
      },
    ],
    vaultDocuments: [
      {
        id: 'demo-doc-1',
        name: 'Sample W-9 (Demo)',
        type: 'w9',
        clientId: '',
        clientName: '',
        projectId: '',
        notes: 'Placeholder document',
        expiryDate: '',
        createdAt: isoDaysAgo(100),
      },
    ],
    subcontractors: [],
    emailTemplates,
    availabilityBlocks: [
      {
        id: 'demo-av-1',
        date: daysAgo(-2),
        startTime: '09:00',
        endTime: '17:00',
        available: true,
        notes: 'Open for new projects',
        createdAt: isoDaysAgo(1),
      },
    ],
    milestones: [
      {
        id: 'demo-ms-1',
        projectId: DEMO_PROJECT_IDS.rebrand,
        projectName: 'Brand Refresh',
        clientId: DEMO_CLIENT_IDS.acme,
        clientName: 'Acme Design Studio',
        title: 'Phase 1 — Discovery',
        percent: 25,
        amount: 3125,
        dueDate: daysAgo(20),
        invoiced: true,
        invoiceId: 'demo-inv-1',
        completed: true,
        createdAt: isoDaysAgo(45),
      },
    ],
    taxSettings: { ...DEFAULT_TAX_SETTINGS },
    integrations: { ...DEFAULT_INTEGRATIONS },
    integrationCredentials: { ...DEFAULT_INTEGRATION_CREDENTIALS, emailFrom: 'demo@workvault-preview.example', emailFromName: contractor },
    calendarSyncMeta: { ...DEFAULT_CALENDAR_SYNC_META },
    bookkeepingSyncMeta: { ...DEFAULT_BOOKKEEPING_SYNC_META },
    schedulingMeta: { ...DEFAULT_SCHEDULING_META },
    plaidSyncMeta: { ...DEFAULT_PLAID_SYNC_META },
    bankTransactions: [],
    gmailInboxCache: [],
    cloudStorageMeta: { ...DEFAULT_CLOUD_STORAGE_META },
    subcontractorPayments: [],
    form1099Records: [],
    tax1099Settings: { ...DEFAULT_TAX1099_SETTINGS },
    activeTimer: null,
    syncMeta: { lastSyncedAt: null, autoSync: false, setupComplete: false },
    demoSettings: {
      enabled: false,
      token: null,
      mode: 'demo',
      expiresAt: null,
      label: 'Client Preview',
      createdAt: null,
      lastAccessedAt: null,
      accessCount: 0,
      projectTransfer: {
        title: '',
        description: '',
        clientNotes: '',
        appPreviewUrl: null,
        deliverables: [],
        updatedAt: null,
      },
      uploadSecret: null,
      allowDownloads: false,
      clientRoom: { ...DEFAULT_CLIENT_ROOM_CONFIG },
    },
    teamMembers: [],
    clientGuestInvites: [],
  }
}
